version: '3.4'

volumes:
  data:
    external: true

services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "Collections"
      POSTGRES_USER: "bot"
      POSTGRES_PASSWORD: "7140043"
      PGDATA: "/var/lib/postgresql/data/data/bd"
    volumes:
      - .:/docker-entrypoint-initdb.d
      - data:/var/lib/postgresql/data
    ports:
      -  5432:5432
  stampytelegrambot:
    image: ${DOCKER_REGISTRY-}stampytelegrambot
    volumes:
      - data:/app/data
      - ./channelsSettings:/app/channelsSettings
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true   
    depends_on:
      - postgres
